In [2]:
import numpy as np
import matplotlib.pyplot as plt 
import scipy as sp 

## 1. Eccentric Anomaly 

<img src="elipse.png">

A planet is moving around the sun in an elliptic Keplerian orbit with semi- major axis $a$, semi-minor axis $b$, and eccentricity $e=\sqrt{1-\frac{a^{2}}{b^{2}}}$. The planet last perihelion occur at $t=0$. The angular frequency of the motion is $\omega =2\pi/T$, where $T$ is the duration of its orbit(period).

If we define a @D coordinate system $(x,y)$ with origin at the center of the ellipse, then the points on the ellipse are decribed by tthe equation 

$$\frac{x^{2}}{a^{2}}+\frac{y^{2}}{b^{2}} = 1$$

the location of the planet in the $(x,y)$ coordinate system is guven by 

$$x = a\sin E$$
$$y=b\sin E$$

where $E$ is the *eccentric anomaly*, whic is defined by 

$$E = \omega t + e\sin E$$

The insteresting equation here is the before equation , which gives an implicit non-linear relations for E. In order to find $E$ for a given $\omega t$ and $e$, we will need to find the solution to the following equation:

$$0 = E-\omega t -e\sin E$$

in other words, we have to find this equation's root!



* The Earth an orbital period of $365.25635$ days, a semi-major axis $a = 1.496\times10^{8}km =1UA$, and it's orbit has an accentricity of $e = 0.0167$. Compute $E$, $x$ and $y$ for $t=91$ days using your favorite root finding method. The fractional method error in $E$ at the end of your computation (from one iteration to the next) should be less than $10^{-10}$. How many iterations does your method need, i.e, how, quickly does it converge ?


## Newton's method 

Let us assumen that equation 

$$f(x) = 0$$

for the real-valued differentiable function $f(x)$ posseses a real zero $\xi$ in the interval $[a,b]$ and that $f'(x)$ and $f''(x)$ are continous and conserve their sign for all $x\in[a,b]$. Starting from an initial approximation $x_{o}$ of the root $\xi$, an improved approximation $x_{1}$ as the $x$-intercept of the tangent line at the curve $y=f(x)$ at the point $(x_{o},f(x_{o}))$. By choosing, in particular $x_{o}=b$, the local derivative $f'(x_{o})$ can be identified with the slope of the tangent line,

$$f'(x_{o}) = \frac{f(x_{o})}{x_{o}-x_{1}}\longrightarrow x_{1} = x_{o}-\frac{f(x_{o})}{f'(x_{o})}$$

Employing the outlined procudure iteratively, one can determine a sequence of approximations $x_{1},x_{2},\cdots$ of the zero $\xi$ of function $f(x)$ based on the *recurrence relation*:

$$x_{i+1} = x_{i} - \frac{f(x_{i})}{f'(x_{i})}\qquad i=0,1,2,\cdots$$

This formula can also be justified by considering the truncated Taylor expansion:

$$f(x_{i+1}) = f(x_{i})+f'(x_{i})(x_{i+1}-x_{i})+\cdots$$

Admitting that $x_{i+1}$ represents an improved approximation, one can consider that $f(x_{i+1})\approx0$ and expresses $x_{i+1}$ to give the recurrence relation

With the absolute correction $\Delta x_{i}$ resulting from the recurrence relation 

$$\Delta x_{i} = x_{i+1}-x_{i}=-\frac{f(x_{i})}{f'(x_{i})}$$

Consistently handing the case $x_{i+1} = 0$ implies the stopping condition as 

$$|\Delta x_{i+1}| = \epsilon|x_{i+1}|$$


In [94]:
def f(x):
    return np.exp(x)*np.log(x)-x*x

def df(x):
    return np.exp(x)*(np.log(x) +1/x)-2*x



def Newton(f,a,b):
    tol = 1e-10; maxiter = 10000
    dx = b-a; x = (b+a)/2.
    h = tol*np.abs(x)
    df = (f(x+h)-f(x))/h
    k = 0
    while(np.abs(dx)>tol and k < maxiter):
        dx = f(x)/df
        x -= dx
        k += 1
    if (k == maxiter):
        print("Root not founded")
    else:
        print ("Was need "+str(k)+" iterations")
        print ("Estimated error "+str(dx))
        return x


        

Find the root

In [80]:
T = 365.25635; w = 2.*np.pi/T
e = 0.0167
t = 0.91
a = 1.496e8
b = a/np.sqrt(1-e**2)

def g(E):
    return E - w*t -e*np.sin(E)

E = Newton(g,0,5)
x = a*np.sin(E)
y = b*np.sin(E)
print ("Eccentric Anomaly ",E)
print ("x = ",x,"km")
print ("y = ",y,"km")

Was need 8 iterations
Estimated error 2.811343878494345e-11
Eccentric Anomaly  0.01591978268622841
x =  2381498.89257819 km
y =  2381831.050169454 km


Now suppose that something happened, putting Earth on a pretty eccentric orbit, say $e=0.99999$. How many iterations does your algorith need now?. How could you accelerate convergence ?

In [79]:
e = 0.99999
E = Newton(g,0,5)
x = a*np.sin(E)
y = b*np.sin(E)
print ("Eccentric Anomaly ",E)
print ("x = ",x,"km")
print ("y = ",y,"km")

Was need 324 iterations
Estimated error 9.895076700110165e-11
Eccentric Anomaly  0.4560967140549896
x =  65890898.848238766 km
y =  65900088.92693912 km


If we need less iterations a way for this is considered a different initial root point. For this is necessary use the taylor expansion

$$0 = E-\omega t -e\sin E \longrightarrow 0=E-\omega t-e\left(E-\frac{E^{3}}{6}+\cdots\right)$$

then

$$E \approx \left(\frac{6\omega t}{e}\right)^{1/3}\approx 0.454561$$

For this reason we choose

$$0.44 < E < 0.46$$

So




In [78]:
e = 0.99999
E = Newton(g,0.44,0.46)
x = a*np.sin(E)
y = b*np.sin(E)
print ("Eccentric Anomaly ",E)
print ("x = ",x,"km")
print ("y = ",y,"km")

Was need 6 iterations
Estimated error 4.3323462725031284e-11
Eccentric Anomaly  0.45609671240945804
x =  65890898.62723126 km
y =  65900088.705900796 km


## 2 Polynomials with multiple Roots

Find all real roots of 

$$f(x) = 3x^{5}+5x^{4}-x^{3}$$

How many are there and how can you construct an algorith that finds all of them?. This method should be general and should work for real roots of any polynomial in one variable with at least on real root. You may ask the internet for help!

Implement your method and be ready to be tested in class to demostrate it's capabilities with a few examples 


In [97]:
def F(x):
    return 3.0*x**5 +5.0*x**4 -x**3

print (Newton(F,0,1))
print (Newton(F,-1,0))



Was need 1151 iterations
Estimated error 9.951894943993126e-11
0.1804604290986747
Root not founded
None


## Birge-Vieta Method

Is the aplication of the Newton-Rhapson method, in particular for determining the zeros of real polynomials. Specifically, we consider the algebraic equation 

$$P_{n}(x) = 0$$

where $P_{n}(x)$ is an n-th degree polnomial with real coefficients

$$P_{n}(x)=a_{o}x^{n}+a_{i}x^{n-1}+\cdots+a_{n-1}x+a_{n}$$

The sequence of approximations of a specific root $\xi$ is given in this case by the recurrence relation 

$$x_{i+1} = x_{i}-\frac{P_{n}(x_{i})}{P'_{n}(x_{i})}\qquad i = 0,1,\cdots$$

and implies the avaluation of both the polynomial and its derivative for the sequence of arguments $x_{i}$, in 
principle, starting from various initial approximations, this relation could be used to determine all the roots. However, the algorithm can be rendered significantly more efficient by using Horner's scheme not only for the implied polynomial evaluations, but asl for reducin the polynomial order by syntetic division once a root is found 


Let $x_{i}$ be the value for wich $P_{n}(x_{i})$ and $P'_{n}(x_{i})$ have to evaluated. According to the *polynomial remainder theorem* , by dividing $P_{n}(x) by the binomial (x-x_{i})$, one obtains a quotient polynomial of order $(n-1)$, $P_{n-1}(x)$, and a remainder , $p_{n}$, which is nonzero if $x_{i}$ is not a zero of $P_{n}(x)$. Accordingly, the synthetic division can be represented as 

$$P_{n}(x) = (x-x_{i})P_{n-1}(x)+p_{n}$$

with 
}
$$P_{n-1}(x) = p_{o}x_{n-1}+p_{1}x^{n-2}+\cdots+p_{n-2}x+p_{n-1}$$

the coefficients p_{n}, can be determined by equating teh expanded expression resulting from the synthetic division :

$$
\left\{
	\begin{array}{ll}
		p_{o}=a_{o}  &  \\
		p_{j}=p_{j-1}x_{i}+a_{j}&
	\end{array}
\right.
$$

Indeed, from the definitions of synthetic division follows that the polynomial value $P_{n}(x_{i})$ is just the remainder of the division of $P_{n}(x)$ by $(x-x_{i})$

$$P_{n}(x_{i}) = p_{n}$$

Turning to the evaluation of the first derivative, $P'_{n}(x)$ results by differentiating the sinthetic division rule 

$$P'_{n}(x) = (x-x_{i})P'_{n-1}(x)+P_{n-1}(x)$$

and , since $P'_{n}(x_{i}) = P_{n-1}(x_{i})$, the evaluation of $P'_{n}(x)$ actually amounts to the evaluation of $P_{n-1(x_{i})}$. By applying Horner's scheme, this calculations consist of iteratively evaluating the numbers 

$$
\left\{
	\begin{array}{ll}
		d_{o}=p_{o}  &  \\
		d_{j}=d_{j-1}x_{i}+p_{j}&
	\end{array}
\right.
$$

which finally yield the desired result:

$$P'_{n}(x_{i})=d_{n-1}$$

Once a root $\xi$ has been determined , the remaining roots can be economically calculated from the reduced polynomial $P_{n-1}(x)$ result from the relations defined before.

The described procedure can be aplied repeatedly, reducing in pararell the polynomial by synthetic division, until all real roots of the initial polynomial $P_{n}(x)$ have been found. 




In [158]:
def BirgeVieta(a,n):
    tol = 1e-10; itemax = 10000
    nx = 0
    roots = np.zeros(n+1)
    if (n <= 1):
        return print("at least a polynomial of the second degree")
    x = 0 
    for m in np.arange(n,1,-1):
        for it in range(1,itemax+1):
            p = a[0]; d = p
            for j in range(1,m):
                p = p*x + a[j]
                d = d*x + p
            p = p*x +a[m]
            if d:
                d = -p/d
            else:
                d =-p
            x+=d
            if(np.abs(d) <= tol*np.abs(x)):
                break
        
        if(it == itemax):
            print("iterations exceeded!") 
        else:
            print ("Was need "+str(it)+" iterations")
            print ("Estimated error "+str(d))
            
        nx +=1
        roots[nx] = x
        
        for j in range(1,m):
            a[j] += a[j-1]*x
    
    nx+=1
    roots[nx] = -a[1]/a[0]
    
    return roots[1:]
        
                

    
BirgeVieta([1,2,1],2)

Was need 28 iterations
Estimated error -0.0


array([-0.99999999, -1.00000001])

Now, we invetigate the polynomial 

$$f(x) = 3x^{5}+5x^{4}-x^{3}$$


In [162]:
Root = BirgeVieta([3,5,-1,0,0,0],5)

Was need 1 iterations
Estimated error 0
Was need 1 iterations
Estimated error 0
Was need 1 iterations
Estimated error -0.0
Was need 5 iterations
Estimated error -1.4601563274517316e-16


In [165]:
print(Root)

[ 0.          0.          0.          0.18046042 -1.84712709]


In [164]:
def pol(x):
    return 3*x**5 + 5*x**4 - x**3

pol(Root)

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.73472348e-18,
       8.88178420e-15])